In [8]:
from scipy.optimize import minimize
def Calculator(x,y,z):
    opt=(x-1)**2+y**2+z**2
    return opt
x=0
x=minimize(Calculator,x,args=(1,3))
print(x)


      fun: 10.0
 hess_inv: array([[0.5]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 6
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([1.00000001])


In [15]:
import numpy as np
i=np.arange(-4,2,0.1)
print(i)
print(10**i)

[-4.00000000e+00 -3.90000000e+00 -3.80000000e+00 -3.70000000e+00
 -3.60000000e+00 -3.50000000e+00 -3.40000000e+00 -3.30000000e+00
 -3.20000000e+00 -3.10000000e+00 -3.00000000e+00 -2.90000000e+00
 -2.80000000e+00 -2.70000000e+00 -2.60000000e+00 -2.50000000e+00
 -2.40000000e+00 -2.30000000e+00 -2.20000000e+00 -2.10000000e+00
 -2.00000000e+00 -1.90000000e+00 -1.80000000e+00 -1.70000000e+00
 -1.60000000e+00 -1.50000000e+00 -1.40000000e+00 -1.30000000e+00
 -1.20000000e+00 -1.10000000e+00 -1.00000000e+00 -9.00000000e-01
 -8.00000000e-01 -7.00000000e-01 -6.00000000e-01 -5.00000000e-01
 -4.00000000e-01 -3.00000000e-01 -2.00000000e-01 -1.00000000e-01
  3.55271368e-15  1.00000000e-01  2.00000000e-01  3.00000000e-01
  4.00000000e-01  5.00000000e-01  6.00000000e-01  7.00000000e-01
  8.00000000e-01  9.00000000e-01  1.00000000e+00  1.10000000e+00
  1.20000000e+00  1.30000000e+00  1.40000000e+00  1.50000000e+00
  1.60000000e+00  1.70000000e+00  1.80000000e+00  1.90000000e+00]
[1.00000000e-04 1.258925

In [18]:
a=[1,2,3]
b=[[4],[5],[6]]
for i, j in enumerate(b):
    print(i)
    print(j)

0
[4]
1
[5]
2
[6]


In [20]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
import numpy as np
x1 = -1 + 2 * np.random.rand(10, 1)
y=np.c_[np.ones([10,1]),x1]
print(y)
z=np.matrix(y)
print(z)

[[ 1.          0.76218966]
 [ 1.         -0.17436087]
 [ 1.         -0.23519531]
 [ 1.         -0.75230992]
 [ 1.         -0.26238671]
 [ 1.         -0.51142349]
 [ 1.          0.57146398]
 [ 1.          0.65175372]
 [ 1.          0.25203345]
 [ 1.         -0.62607003]]
[[ 1.          0.76218966]
 [ 1.         -0.17436087]
 [ 1.         -0.23519531]
 [ 1.         -0.75230992]
 [ 1.         -0.26238671]
 [ 1.         -0.51142349]
 [ 1.          0.57146398]
 [ 1.          0.65175372]
 [ 1.          0.25203345]
 [ 1.         -0.62607003]]


In [18]:
d=np.random.normal(3,1,(10,1))
d=np.matrix(d)
d=np.exp(d)
print(d)

[[63.74566907]
 [27.52614302]
 [12.41860625]
 [16.01620096]
 [49.97045545]
 [30.6731009 ]
 [44.26997328]
 [34.19870264]
 [27.64137152]
 [51.65634676]]


In [3]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[4,5,6],[7,8,9],[10,11,12]])
C=np.array([  [(A[i,j]+B[i,j]) for j in range(B.shape[1]) ] for i in range(B.shape[0])  ])
print(C)
